version: 2.1

orbs:
  cypress: cypress-io/cypress@1.10.0
  heroku_sandbox: rise/deploy-to-heroku@0.0.6
  heroku_staging: rise/deploy-to-heroku@0.0.6
  heroku_production: rise/deploy-to-heroku@0.0.6

workflows:
  build_test_deploy:
    jobs:
      - cypress/run:
          build: 'npm run build'
          start: 'node __sapper__/build'
          post-steps:
            - store_test_results:
                path: cypress/results
      - heroku_sandbox:
          requires:
            - cypress/run
          filters:
            branches:
              only: master
      - heroku_staging:
          requires:
            - cypress/run
          filters:
            branches:
              only: master
      - heroku_production:
          requires:
            - cypress/run
          filters:
            tags:
              only: /^v*/
            branches:
              only: master

jobs:
  build:
    working_directory: ~/rise
    docker:
      - image: circleci/node:12-browsers
        environment:
          CHROME_BIN: '/usr/bin/google-chrome'
          TZ: 'America/Los_Angeles'
    environment:
      TZ: 'America/Los_Angeles'
    steps:
      - checkout
      - run:
          name: update npm
          command: 'sudo npm install -g npm@6'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: npm install
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: unit tests
          command: npm run test
      - store_test_results:
          path: test-results

  heroku_sandbox:
    executor: heroku_sandbox/node # Uses the basic buildpack-deps image, which has the prerequisites for installing heroku's CLI.
    steps:
      - heroku_sandbox/setup
      - heroku_sandbox/install_dependencies
      - heroku_sandbox/docker-build-release:
          app-name: $HEROKU_APP_NAME_SANDBOX
          app-arg: NODE_ENV=development,SITE_URL=https://app.sandbox.rise.com,API_URL=https://api.sandbox.rise.com,API_URL_TEST=https://api.sandbox.rise.com,RISE_API_PUBLIC=pk_00000000-0000-0000-0000-000000000000,RISE_DEFAULT_CHANNEL=00000000-0000-0000-0000-000000000000,NPM_CONFIG_PRODUCTION=false,GATEWAY_UUID=,GATEWAY_PUBLIC=
          app-type: $HEROKU_APP_NAME_TYPE

  heroku_staging:
    executor: heroku_staging/node # Uses the basic buildpack-deps image, which has the prerequisites for installing heroku's CLI.
    steps:
      - heroku_staging/setup
      - heroku_staging/install_dependencies
      - heroku_staging/docker-build-release:
          app-name: $HEROKU_APP_NAME_STAGING
          app-arg: NODE_ENV=development,SITE_URL=https://app.beta.rise.com,API_URL=https://api.beta.rise.com,API_URL_TEST=https://api.beta.rise.com,RISE_API_PUBLIC=pk_00000000-0000-0000-0000-000000000000,RISE_DEFAULT_CHANNEL=00000000-0000-0000-0000-000000000000,NPM_CONFIG_PRODUCTION=false,GATEWAY_UUID=,GATEWAY_PUBLIC=
          app-type: $HEROKU_APP_NAME_TYPE

  heroku_production:
    executor: heroku_production/node # Uses the basic buildpack-deps image, which has the prerequisites for installing heroku's CLI.
    steps:
      - heroku_production/setup
      - heroku_production/install_dependencies
      - heroku_production/docker-build-release:
          app-name: $HEROKU_APP_NAME
          app-arg: NODE_ENV=production,SITE_URL=https://app.rise.com,API_URL=https://api.rise.com,API_URL_TEST=https://api.beta.rise.com,RISE_API_PUBLIC=pk_00000000-0000-0000-0000-000000000000,RISE_DEFAULT_CHANNEL=00000000-0000-0000-0000-000000000000,NPM_CONFIG_PRODUCTION=false,GATEWAY_UUID=,GATEWAY_PUBLIC=
          app-type: $HEROKU_APP_NAME_TYPE
