version: 2.1

orbs:
  cypress: cypress-io/cypress@1.10.0
  heroku_sandbox: rise/deploy-to-heroku@0.0.6

workflows:
  build_test_deploy:
    jobs:
      - cypress/run:
          build: 'npm run build'
          start: 'node __sapper__/build'
          post-steps:
            - store_test_results:
                path: cypress/results
      - heroku_sandbox:
          requires:
            - cypress/run
          filters:
            branches:
              only: master

jobs:
  build:
    working_directory: ~/rise
    docker:
      - image: circleci/node:12-browsers
        environment:
          CHROME_BIN: '/usr/bin/google-chrome'
          TZ: 'America/Los_Angeles'
    environment:
      TZ: 'America/Los_Angeles'
    steps:
      - checkout
      - run:
          name: update npm
          command: 'sudo npm install -g npm@6'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: npm install
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: unit tests
          command: npm run test
      - store_test_results:
          path: test-results

  heroku_sandbox:
    executor: heroku_sandbox/node # Uses the basic buildpack-deps image, which has the prerequisites for installing heroku's CLI.
    steps:
      - heroku_sandbox/setup
      - heroku_sandbox/install_dependencies
      - heroku_sandbox/docker-build-release:
          app-name: $HEROKU_APP_NAME_SANDBOX
          app-arg: NODE_ENV=development,SITE_URL=https://demo.sandbox.rise.store,API_URL=https://api.sandbox.rise.store,API_URL_TEST=https://api.sandbox.rise.store,RISE_API_PUBLIC=pk_test_c4beb40b-1651-48ef-a821-c28a81e98ade,RISE_DEFAULT_CHANNEL=c034ad64-87c9-479c-ae5e-8c9aedf0b1f3,NPM_CONFIG_PRODUCTION=false,GATEWAY_UUID=,GATEWAY_PUBLIC=
          app-type: $HEROKU_APP_NAME_TYPE
